version: 0.15.0-{build}
platform:
  - x64
environment:
  RUST_INSTALL_DIR: C:\Rust
  matrix:
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-msvc
      RUST_VERSION: 1.7.0
install:
   # Rust
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-$Env:RUST_VERSION-$Env:RUST_INSTALL_TRIPLE.msi"
  - cmd: start /wait msiexec /i rust-%RUST_VERSION%-%RUST_INSTALL_TRIPLE%.msi INSTALLDIR="%RUST_INSTALL_DIR%" /quiet /qn /norestart
  - cmd: SET PATH=%PATH%;%RUST_INSTALL_DIR%\bin
  - rustc --version
  - cargo --version
  # Qt
  - set QTDIR=C:\Qt\5.4\msvc2013_64_opengl
  - set PATH=%QTDIR%\bin;%PATH%
  - set CMAKE_PREFIX_PATH=%QTDIR%;%CMAKE_PREFIX_PATH%
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
  - cargo build --verbose
test_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
  - cargo test --verbose
