os: unstable
version: 0.13.0-{build}
platform:
  - x64
environment:
  RUST_INSTALL_DIR: C:\Rust
  matrix:
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-msvc
      RUST_VERSION: 1.7.0
install:
   # Rust
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-$Env:RUST_VERSION-$Env:RUST_INSTALL_TRIPLE.exe"
  - cmd: rust-%RUST_VERSION%-%RUST_INSTALL_TRIPLE%.exe /VERYSILENT /NORESTART /COMPONENTS="rust,cargo" /DIR="%RUST_INSTALL_DIR%"
  - cmd: SET PATH=%PATH%;%RUST_INSTALL_DIR%\bin
  - rustc --version
  - cargo --version
  # Qt
  - set QTDIR=C:\Qt\5.4\msvc2013_64_opengl
  - set PATH=%QTDIR%\bin;%PATH%
  - set CMAKE_PREFIX_PATH=%QTDIR%;%CMAKE_PREFIX_PATH%
  # GLPK
  - ps: Start-FileDownload "http://downloads.sourceforge.net/project/winglpk/winglpk/GLPK-4.55/winglpk-4.55.zip"
  - cmd: 7z x winglpk-4.55.zip
  - set LIB=%LIB%;C:\projects\panopticon\glpk-4.55\w64
  - set PATH=%PATH%;C:\projects\panopticon\glpk-4.55\w64
  - cmd: ren glpk-4.55\w64\glpk_4_55.lib glpk.lib
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
  - cargo build --verbose
test_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
  - cargo test --verbose
