[package]
name = "panopticon"
version = "0.1.0"
authors = ["seu <seu@panopticon.re>"]

[lib]
name = "panopticon"
path = "lib/src/lib.rs"
test = true

[[bin]]
name = "qtpanopticon"
path = "qt/src/main.rs"

[dependencies]
log = "*"
rustc-serialize = "*"
num = "*"
tempdir = "*"
lazy_static = "*"
libc = "*"
uuid = "*"

[dependencies.qmlrs]
git = "https://github.com/flanfly/qmlrs"

[dependencies.msgpack]
git = "https://github.com/neonquill/rust-msgpack.git"
branch = "rust_1.0.0_for_merge"

[dependencies.graph_algos]
git = "https://github.com/flanfly/rust-graph-algos.git"
