[package]
name = "panopticon"
version = "0.12.0"
authors = ["seu <seu@panopticon.re>"]

[lib]
name = "panopticon"
path = "lib/src/lib.rs"
test = true

[[bin]]
name = "qtpanopticon"
path = "qt/src/main.rs"

[dependencies]
log = "*"
rustc-serialize = "*"
num = "*"
tempdir = "*"
lazy_static = "*"
libc = "*"
uuid = "*"
glpk-sys = "*"
flate2 = "*"
rmp-serialize = "*"
byteorder = "*"

[dependencies.qmlrs]
git = "https://github.com/flanfly/qmlrs"

[dependencies.graph_algos]
git = "https://github.com/flanfly/rust-graph-algos.git"
