[package]
name = "panopticon"
version = "0.1.0"
authors = ["seu <seu@panopticon.re>"]

[lib]
name = "panopticon"
path = "lib/src/lib.rs"
crate-type = ["dylib"]
plugin = true # needed to force dynamic linking
test = true

[[bin]]
name = "qtpanopticon"
path = "qt/src/main.rs"

[dependencies]
log = "*"
rustc-serialize = "*"

[dependencies.qmlrs]
git = "https://github.com/cyndis/qmlrs"

[dependencies.msgpack]
git = "https://github.com/neonquill/rust-msgpack.git"
branch = "rust_1.0.0_for_merge"
