max_width=1000
fn_call_width=1000
chain_one_line_max=100
reorder_imports=true
reorder_imported_names=true
fn_args_layout = "Block"
array_layout = "Block"
where_style = "Rfc"
generics_indent = "Block"
fn_call_style = "Block"
